{% set name = "perl-json-pp" %}
{% set version = "4.12" %}
{% set sha256 = "fb76b443f65820452732ba74647a459d61fb61ecce920b19d6f9b881948439de" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/I/IS/ISHIGAKI/JSON-PP-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script:
    - perl Makefile.PL INSTALLDIRS=vendor NO_PERLLOCAL=1 NO_PACKLIST=1
    - make
    - make test
    - make install VERBINST=1

requirements:
  build:
    - make
  host:
    - perl
    - perl-extutils-makemaker
  run:
    - perl

test:
  imports:
    - JSON::PP
    - JSON::PP::Boolean

about:
  home: https://metacpan.org/dist/JSON-PP
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_family: OTHER
  summary: JSON::XS compatible pure-Perl module.
  license_file:
    - {{ environ["PREFIX"] }}/man/man1/perlartistic.1
    - {{ environ["PREFIX"] }}/man/man1/perlgpl.1

extra:
  recipe-maintainers:
    - cbrueffer
